### ISSUE TITLE
temp folders not created. 

### ISSUE THREAD

**Issue by wedgen** [im-0/arm-image-installer#2]
https://github.com/im-0/arm-image-installer/blob/fee9b3d5ee78bae0a6d7aad05f5e901fb99d4d7d/arm-image-installer#L422

This line creates a new folder `{boot,root,fw}`, not the desired boot/ root/ fw/
on "Raspbian GNU/Linux 11 (bullseye)"

**Comment by im-0** [comment]
This is an old unmaintained fork with private patches. Upstream is there: https://pagure.io/arm-image-installer
